package cart.com.entity;
// Generated 15-may-2016 19:15:35 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;

/**
 * DetalleOrden generated by hbm2java
 */
public class DetalleOrden implements java.io.Serializable {

	private int idDetalle;
	private Orden orden;
	private Producto producto;
	private String descripcion;
	private Integer cantidad;
	private BigDecimal precio;

	public DetalleOrden() {
	}

	public DetalleOrden(int idDetalle) {
		this.idDetalle = idDetalle;
	}

	public DetalleOrden(int idDetalle, Orden orden, Producto producto, String descripcion, Integer cantidad,
			BigDecimal precio) {
		this.idDetalle = idDetalle;
		this.orden = orden;
		this.producto = producto;
		this.descripcion = descripcion;
		this.cantidad = cantidad;
		this.precio = precio;
	}

	public int getIdDetalle() {
		return this.idDetalle;
	}

	public void setIdDetalle(int idDetalle) {
		this.idDetalle = idDetalle;
	}

	public Orden getOrden() {
		return this.orden;
	}

	public void setOrden(Orden orden) {
		this.orden = orden;
	}

	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Integer getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Integer cantidad) {
		this.cantidad = cantidad;
	}

	public BigDecimal getPrecio() {
		return this.precio;
	}

	public void setPrecio(BigDecimal precio) {
		this.precio = precio;
	}

}
