package cart.com.entity;
// Generated 18-jul-2016 22:56:46 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Establecimiento generated by hbm2java
 */
public class Establecimiento implements java.io.Serializable {

	private int idEstablecimiento;
	private String ruc;
	private String nombre;
	private String email;
	private String contrasena;
	private String telefono;
	private Set ordens = new HashSet(0);
	private Set productos = new HashSet(0);

	public Establecimiento() {
	}

	public Establecimiento(int idEstablecimiento) {
		this.idEstablecimiento = idEstablecimiento;
	}

	public Establecimiento(int idEstablecimiento, String ruc, String nombre, String email, String contrasena,
			String telefono, Set ordens, Set productos) {
		this.idEstablecimiento = idEstablecimiento;
		this.ruc = ruc;
		this.nombre = nombre;
		this.email = email;
		this.contrasena = contrasena;
		this.telefono = telefono;
		this.ordens = ordens;
		this.productos = productos;
	}

	public int getIdEstablecimiento() {
		return this.idEstablecimiento;
	}

	public void setIdEstablecimiento(int idEstablecimiento) {
		this.idEstablecimiento = idEstablecimiento;
	}

	public String getRuc() {
		return this.ruc;
	}

	public void setRuc(String ruc) {
		this.ruc = ruc;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getContrasena() {
		return this.contrasena;
	}

	public void setContrasena(String contrasena) {
		this.contrasena = contrasena;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public Set getOrdens() {
		return this.ordens;
	}

	public void setOrdens(Set ordens) {
		this.ordens = ordens;
	}

	public Set getProductos() {
		return this.productos;
	}

	public void setProductos(Set productos) {
		this.productos = productos;
	}

}
