package cart.com.entity;
// Generated 18-jul-2016 22:56:46 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Orden generated by hbm2java
 */
public class Orden implements java.io.Serializable {

	private int idOrden;
	private Establecimiento establecimiento;
	private String celular;
	private BigDecimal monto;
	private Set detalleOrdens = new HashSet(0);

	public Orden() {
	}

	public Orden(int idOrden) {
		this.idOrden = idOrden;
	}

	public Orden(int idOrden, Establecimiento establecimiento, String celular, BigDecimal monto, Set detalleOrdens) {
		this.idOrden = idOrden;
		this.establecimiento = establecimiento;
		this.celular = celular;
		this.monto = monto;
		this.detalleOrdens = detalleOrdens;
	}

	public int getIdOrden() {
		return this.idOrden;
	}

	public void setIdOrden(int idOrden) {
		this.idOrden = idOrden;
	}

	public Establecimiento getEstablecimiento() {
		return this.establecimiento;
	}

	public void setEstablecimiento(Establecimiento establecimiento) {
		this.establecimiento = establecimiento;
	}

	public String getCelular() {
		return this.celular;
	}

	public void setCelular(String celular) {
		this.celular = celular;
	}

	public BigDecimal getMonto() {
		return this.monto;
	}

	public void setMonto(BigDecimal monto) {
		this.monto = monto;
	}

	public Set getDetalleOrdens() {
		return this.detalleOrdens;
	}

	public void setDetalleOrdens(Set detalleOrdens) {
		this.detalleOrdens = detalleOrdens;
	}

}
