package cart.com.entity;
// Generated 15-may-2016 19:15:35 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto implements java.io.Serializable {

	private int idProducto;
	private Establecimiento establecimiento;
	private String descripcion;
	private BigDecimal precio;
	private String nombre;
	private Set<DetalleOrden> detalleOrdens = new HashSet<DetalleOrden>(0);

	public Producto() {
	}

	public Producto(int idProducto) {
		this.idProducto = idProducto;
	}

	public Producto(int idProducto, Establecimiento establecimiento, String descripcion, BigDecimal precio,
			String nombre, Set<DetalleOrden> detalleOrdens) {
		this.idProducto = idProducto;
		this.establecimiento = establecimiento;
		this.descripcion = descripcion;
		this.precio = precio;
		this.nombre = nombre;
		this.detalleOrdens = detalleOrdens;
	}

	public int getIdProducto() {
		return this.idProducto;
	}

	public void setIdProducto(int idProducto) {
		this.idProducto = idProducto;
	}

	public Establecimiento getEstablecimiento() {
		return this.establecimiento;
	}

	public void setEstablecimiento(Establecimiento establecimiento) {
		this.establecimiento = establecimiento;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public BigDecimal getPrecio() {
		return this.precio;
	}

	public void setPrecio(BigDecimal precio) {
		this.precio = precio;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set<DetalleOrden> getDetalleOrdens() {
		return this.detalleOrdens;
	}

	public void setDetalleOrdens(Set<DetalleOrden> detalleOrdens) {
		this.detalleOrdens = detalleOrdens;
	}

}
