package cart.com.entity;
// Generated 18-jul-2016 22:56:46 by Hibernate Tools 4.3.1.Final

/**
 * UserRole generated by hbm2java
 */
public class UserRole implements java.io.Serializable {

	private UserRoleId id;

	public UserRole() {
	}

	public UserRole(UserRoleId id) {
		this.id = id;
	}

	public UserRoleId getId() {
		return this.id;
	}

	public void setId(UserRoleId id) {
		this.id = id;
	}

}
