package cart.com.entity;
// Generated 18-jul-2016 22:56:46 by Hibernate Tools 4.3.1.Final

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private String userId;
	private Integer active;
	private String emailId;
	private String name;
	private String password;
	private String provider;

	public User() {
	}

	public User(String userId) {
		this.userId = userId;
	}

	public User(String userId, Integer active, String emailId, String name, String password, String provider) {
		this.userId = userId;
		this.active = active;
		this.emailId = emailId;
		this.name = name;
		this.password = password;
		this.provider = provider;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public Integer getActive() {
		return this.active;
	}

	public void setActive(Integer active) {
		this.active = active;
	}

	public String getEmailId() {
		return this.emailId;
	}

	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getProvider() {
		return this.provider;
	}

	public void setProvider(String provider) {
		this.provider = provider;
	}

}
